spring.application.name=quily
spring.datasource.url=jdbc:mysql://quily.cf0y62oqk0ot.eu-north-1.rds.amazonaws.com:3306/Quily
spring.datasource.username=admin
spring.datasource.password=Nisar#123#
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update