spring.application.name=quily
spring.r2dbc.url=r2dbc:mysql://quily.cf0y62oqk0ot.eu-north-1.rds.amazonaws.com:3306/Quily
spring.r2dbc.username=admin
spring.r2dbc.password=Nisar#123#
spring.r2dbc.pool.enabled=true
server.port=8081