spring.application.name=quily
spring.datasource.url=jdbc:mysql://localhost:3306/Test
spring.datasource.username=root
spring.datasource.password=Nisar#123#
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#Key generator field
HashStringLength = 6
BaseSize = 62

Base62_1 = mkKVUs0DQjxfMOLhe2HclrS183ZCPydYEwNJRt7IvuqWF9z65pbonBa4AiGgXT
Base62_2 = Y7LnRwDTbzio5Vjhf8GZN0HmcFEyp9Xuga6W2UPql3ABJdrCSI4tQO1MKeskvx
Base62_3 = SWUKYIEkjNo9lVyhzZv1mg0Tipf2wHrC5anx3RuOcG4PdsebF8JXQDt7MLAq6B
Base62_4 = rgv0ubZdSf21WtUAsGh7p3YNax5QBcTPXR4LKk8HoeMjm6znIqV9OywlDCJEFi
Base62_5 = CFVTYfpIqo6zkGPOAiLWHcemdrRMnStv7lBDJa2Z1jsyKu84wE5xhQNX93gU0b
Base62_6 = EqSIFVbuXDZPlpWYnKTmOi7cA3ew0Uhy1Qt84gkBdz2RfJoGaxv5s6Cjr9HNLM

KeyGeneratedIndicesId = 1