package com.example.quily.model;
import jakarta.persistence.*;
import java.util.Date;

@Entity
@Table(name = "TestUsers") // This is the table name
public class User {

    @Id //'@Id'This annotation indicates that the field userID is the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY) //This annotation specifies the strategy for the generation of the primary key values. In this case, GenerationType.IDENTITY indicates that the primary key values will be automatically generated by the underlying database. This typically corresponds to an auto-incremented column in the database.
    @Column(name = "UserID") //This annotation specifies the column name in the database table that corresponds to the userID field in the entity class.
    private int userID;

    @Column(name = "FirstName", nullable = false, length = 30) //When we pass column name Like "FirstName" then in DB Field is automatically Convert Like "FirstName""
    private String firstName;

    @Column(name = "MiddleName", length = 30)
    private String middleName;

    @Column(name = "LastName", length = 30)
    private String lastName;

    @Column(name = "Email", nullable = false, unique = true, length = 30)
    private String email;

    @Column(name = "MobileNumber", unique = true, length = 30)
    private String mobileNumber;

    @Column(name = "AccountCreationDate", nullable = false)
    private Date accountCreationDate;

    @Column(name = "Active", nullable = false)
    private boolean active;

    @Column(name = "UserType", length = 10)
    private String userType;

    // Constructors, getters, and setters
    // Constructor
    public User() {
    }


    public User(String firstName, String middleName, String lastName, String email,
                String mobileNumber, Date accountCreationDate, boolean active, String userType) {
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.email = email;
        this.mobileNumber = mobileNumber;
        this.accountCreationDate = accountCreationDate;
        this.active = active;
        this.userType = userType;
    }
}
